# Dockerfile which provides the search engine

FROM docker.elastic.co/elasticsearch/elasticsearch:7.16.3

ENV discovery.type=single-node

# Finalize elasticsearch installation
ADD config/elasticsearch.yml /etc/elasticsearch/
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu

ENV ES_HEAP_SIZE=1g
ENV ES_JAVA_OPTS="-Xms512m -Xmx512m"
